# Site
repository: sproogen/resume-theme
# favicon: images/favicon.ico

# Personal info
name: Cuiyun Gao
title: Research Fellow
email: cuiyun.gao@ntu.edu.sg
website: cuiyungao.github.io

# Social links
# twitter_username: facespics
github_username:  cuiyungao
# dribbble_username: jekyll
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: chillwildlife
# linkedin_username: jameswgrant
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  I'm now working as a PostDoc in NTU (Nanyang Technology University) in Singapore. Prior to joining NTU, I used to work as a PostDoc in CUHK, working with Prof. Michael R. Lyu. I also received my PhD degree at CUHK, and graduated in end of 2018. Before coming to CUHK, I was one bachelor student of the Department of Communication Engineering of Shanghai University (SHU) in 2012~2014, under the supervision of Prof. Wanggen WAN. Before starting my engineering career, I joined Chien Wei-zang College (钱伟长学院) in 2010, an Honors College of SHU, and graduated from the College in 2012.

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: A Little More About Me
more_content: | # this will include new lines to allow paragraphs
  Alongside my research interests, some of my other interests and hobbies are:
   - Jogging
   - Swimming
   - Playing badminton
   - Climing montains
   - Yoga
   - Travelling

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
